package gitrepository

import (
	"reflect"
	"testing"
)

func TestGitRepository_GithubParse(t *testing.T) {
	tests := []struct {
		name    string
		url     string
		branch  string
		sub     string
		wantObj *GitRepository
		wantErr bool
	}{
		{
			name:   "Parse Github Current Branch Repository",
			url:    "https://github.com/cli/cli",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli",
				RawUrl:       "https://github.com/cli/cli",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli",
				DirPath:      "repository/cli/cli/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli",
				Path:         "",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Different Branch Repository",
			url:    "https://github.com/cli/cli/tree/bad-branch",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/tree/bad-branch",
				RawUrl:       "https://github.com/cli/cli/tree/bad-branch",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/bad-branch/",
				DirPath:      "repository/cli/cli/bad-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/tree/bad-branch",
				Path:         "",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "bad-branch",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/bad-branch.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/bad-branch/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Repository Some Folder",
			url:    "https://github.com/cli/cli/tree/bad-branch/cmd",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/tree/bad-branch/cmd",
				RawUrl:       "https://github.com/cli/cli/tree/bad-branch/cmd",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/bad-branch/cmd/",
				DirPath:      "repository/cli/cli/bad-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/tree/bad-branch/cmd",
				Path:         "cmd",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "bad-branch",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/bad-branch.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/bad-branch/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Repository Multiple Folders",
			url:    "https://github.com/cli/cli/tree/bad-branch/cmd/gh",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/tree/bad-branch/cmd/gh",
				RawUrl:       "https://github.com/cli/cli/tree/bad-branch/cmd/gh",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/bad-branch/cmd/gh/",
				DirPath:      "repository/cli/cli/bad-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/tree/bad-branch/cmd/gh",
				Path:         "cmd/gh",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "bad-branch",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/bad-branch.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/bad-branch/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Repository Multiple Folders - 2",
			url:    "https://github.com/cli/cli/blob/develop/services/website-constellation/gatsby-node.js",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/blob/develop/services/website-constellation/gatsby-node.js",
				RawUrl:       "https://github.com/cli/cli/blob/develop/services/website-constellation/gatsby-node.js",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/develop/services/website-constellation/",
				DirPath:      "repository/cli/cli/develop",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/blob/develop/services/website-constellation/gatsby-node.js",
				Path:         "services/website-constellation/gatsby-node.js",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "develop",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/develop.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/develop/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Slashes Repository Name Before Define",
			url:    "https://github.com/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation",
			branch: "ckharrl/CONCLOUD-68878-close-manager-propagation",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation",
				RawUrl:       "https://github.com/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation/",
				DirPath:      "repository/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation",
				Path:         "",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Root Directory Single File",
			url:    "https://github.com/cli/cli/blob/trunk/Makefile",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/blob/trunk/Makefile",
				RawUrl:       "https://github.com/cli/cli/blob/trunk/Makefile",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/trunk/",
				DirPath:      "repository/cli/cli/trunk",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/blob/trunk/Makefile",
				Path:         "Makefile",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "trunk",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/trunk.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/trunk/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		/*{
			name:   "Parse Github Slashes Repository Name",
			url:    "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
			branch: "",
			sub: "",
			wantObj: &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				RawUrl:      "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				CloneUrl:    "https://github.com/cli/cli.git",
				RemoteUrl:   "git@github.com:cli/cli.git",
				DirPath:     "repository/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:      true,
				Protocol:    "https",
				Scheme:      "https",
				Hostname:    "github.com",
				RawPath:     "/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				Path:        "",
				Owner:       "cli",
				Name:        "cli",
				DummyBranch: "gitd-branch",
				Branch:      "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:  "https://github.com/cli/cli/archive/refs/heads/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:     "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
			},
			wantErr: false,
		},*/
		{
			name:   "Parse Github Slashes Repository Name File",
			url:    "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
			branch: "ckharrl/CONCLOUD-68878-close-manager-propagation",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				RawUrl:       "https://github.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli/tree/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/",
				DirPath:      "repository/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				Path:         "services/website-constellation/gatsby-node.js",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Repository Fragment Url",
			url:    "https://github.com/cli/cli/#browser-support",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://github.com/cli/cli",
				RawUrl:       "https://github.com/cli/cli/#browser-support",
				CloneUrl:     "https://github.com/cli/cli.git",
				RemoteUrl:    "git@github.com:cli/cli.git",
				QueryUrl:     "https://github.com/cli/cli",
				DirPath:      "repository/cli/cli/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "github.com",
				RawPath:      "/cli/cli",
				Path:         "",
				Owner:        "cli",
				Name:         "cli",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://github.com/cli/cli/archive/refs/heads/.zip",
				FileUrl:      "https://raw.githubusercontent.com/cli/cli//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "",
				RawUrl:      tt.url,
				CloneUrl:    "",
				RemoteUrl:   "",
				DirPath:     "",
				IsFile:      false,
				Protocol:    "",
				Scheme:      "",
				Hostname:    "",
				RawPath:     "",
				Path:        "",
				Owner:       "",
				Name:        "",
				DummyBranch: "gitd-branch",
				Branch:      tt.branch,
				ArchiveUrl:  "",
				FileUrl:     "",
			}
			if err := r.Parse(tt.sub, DirectionNone, ""); (err != nil) != tt.wantErr {
				t.Errorf("GitRepository.Parse() error = %#v, wantErr %#v", err, tt.wantErr)
			}

			if !reflect.DeepEqual(r, tt.wantObj) {
				t.Errorf("DeepEqual r = %#v, wantObj %#v", r, tt.wantObj)
			}
		})
	}
}

func TestGitRepository_GitlabParse(t *testing.T) {
	tests := []struct {
		name    string
		url     string
		branch  string
		sub     string
		wantObj *GitRepository
		wantErr bool
	}{
		{
			name:   "Parse Gitlab Current Branch Repository",
			url:    "https://gitlab.com/gitlab-org/gitlab",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab",
				DirPath:      "repository/gitlab-org/gitlab/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab",
				Path:         "",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive//gitlab-.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Different Branch Repository",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/tree/dc-move-assignees-widget",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/",
				DirPath:      "repository/gitlab-org/gitlab/dc-move-assignees-widget",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/tree/dc-move-assignees-widget",
				Path:         "",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "dc-move-assignees-widget",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/dc-move-assignees-widget/gitlab-dc-move-assignees-widget.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/dc-move-assignees-widget/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Repository Some Folder",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/tree/dc-move-assignees-widget/metrics_server",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/metrics_server",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/metrics_server",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/metrics_server/",
				DirPath:      "repository/gitlab-org/gitlab/dc-move-assignees-widget",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/tree/dc-move-assignees-widget/metrics_server",
				Path:         "metrics_server",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "dc-move-assignees-widget",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/dc-move-assignees-widget/gitlab-dc-move-assignees-widget.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/dc-move-assignees-widget/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Repository Multiple Folders",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/tree/dc-move-assignees-widget/db/fixtures",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/db/fixtures",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/db/fixtures",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/db/fixtures/",
				DirPath:      "repository/gitlab-org/gitlab/dc-move-assignees-widget",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/tree/dc-move-assignees-widget/db/fixtures",
				Path:         "db/fixtures",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "dc-move-assignees-widget",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/dc-move-assignees-widget/gitlab-dc-move-assignees-widget.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/dc-move-assignees-widget/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Repository Multiple Folders - 2",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/blob/dc-move-assignees-widget/db/migrate/20210301200959_init_schema.rb",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/blob/dc-move-assignees-widget/db/migrate/20210301200959_init_schema.rb",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/blob/dc-move-assignees-widget/db/migrate/20210301200959_init_schema.rb",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/dc-move-assignees-widget/db/migrate/",
				DirPath:      "repository/gitlab-org/gitlab/dc-move-assignees-widget",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/blob/dc-move-assignees-widget/db/migrate/20210301200959_init_schema.rb",
				Path:         "db/migrate/20210301200959_init_schema.rb",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "dc-move-assignees-widget",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/dc-move-assignees-widget/gitlab-dc-move-assignees-widget.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/dc-move-assignees-widget/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Slashes Repository Name Before Define",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/tree/ss/add-community-docs",
			branch: "ss/add-community-docs",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/tree/ss/add-community-docs",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/tree/ss/add-community-docs",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/ss/add-community-docs/",
				DirPath:      "repository/gitlab-org/gitlab/ss/add-community-docs",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/tree/ss/add-community-docs",
				Path:         "",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "ss/add-community-docs",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/ss/add-community-docs/gitlab-ss-add-community-docs.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/ss/add-community-docs/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Root Directory Single File",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/blob/master/Dangerfile",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/blob/master/Dangerfile",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/blob/master/Dangerfile",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/master/",
				DirPath:      "repository/gitlab-org/gitlab/master",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/blob/master/Dangerfile",
				Path:         "Dangerfile",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "master",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/master/gitlab-master.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/master/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		/*{
			name:   "Parse Github Slashes Repository Name",
			url:    "https://gitlab.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
			branch: "",
			sub: "",
			wantObj: &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "https://gitlab.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				RawUrl:      "https://gitlab.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				CloneUrl:    "https://gitlab.com/cli/cli.git",
				RemoteUrl:   "git@gitlab.com:cli/cli.git",
				DirPath:     "repository/cli/cli/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:      true,
				Protocol:    "https",
				Scheme:      "https",
				Hostname:    "gitlab.com",
				RawPath:     "/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				Path:        "",
				Owner:       "cli",
				Name:        "cli",
				DummyBranch: "gitd-branch",
				Branch:      "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:  "https://gitlab.com/cli/cli/archive/refs/heads/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:     "https://gitlab.com/cli/cli/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
			},
			wantErr: false,
		},*/
		{
			name:   "Parse Gitlab Slashes Repository Name File",
			url:    "https://gitlab.com/gitlab-org/gitlab/-/blob/ss/add-community-docs/app/mailers/abuse_report_mailer.rb",
			branch: "ss/add-community-docs",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab/blob/ss/add-community-docs/app/mailers/abuse_report_mailer.rb",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/blob/ss/add-community-docs/app/mailers/abuse_report_mailer.rb",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab/tree/ss/add-community-docs/app/mailers/",
				DirPath:      "repository/gitlab-org/gitlab/ss/add-community-docs",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab/blob/ss/add-community-docs/app/mailers/abuse_report_mailer.rb",
				Path:         "app/mailers/abuse_report_mailer.rb",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "ss/add-community-docs",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive/ss/add-community-docs/gitlab-ss-add-community-docs.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw/ss/add-community-docs/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Github Repository Fragment Url",
			url:    "https://gitlab.com/gitlab-org/gitlab/#browser-support",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://gitlab.com/gitlab-org/gitlab",
				RawUrl:       "https://gitlab.com/gitlab-org/gitlab/#browser-support",
				CloneUrl:     "https://gitlab.com/gitlab-org/gitlab.git",
				RemoteUrl:    "git@gitlab.com:gitlab-org/gitlab.git",
				QueryUrl:     "https://gitlab.com/gitlab-org/gitlab",
				DirPath:      "repository/gitlab-org/gitlab/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "gitlab.com",
				RawPath:      "/gitlab-org/gitlab",
				Path:         "",
				Owner:        "gitlab-org",
				Name:         "gitlab",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://gitlab.com/gitlab-org/gitlab/-/archive//gitlab-.zip",
				FileUrl:      "https://gitlab.com/gitlab-org/gitlab/-/raw//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "",
				RawUrl:      tt.url,
				CloneUrl:    "",
				RemoteUrl:   "",
				DirPath:     "",
				IsFile:      false,
				Protocol:    "",
				Scheme:      "",
				Hostname:    "",
				RawPath:     "",
				Path:        "",
				Owner:       "",
				Name:        "",
				DummyBranch: "gitd-branch",
				Branch:      tt.branch,
				ArchiveUrl:  "",
				FileUrl:     "",
			}
			if err := r.Parse(tt.sub, DirectionNone, ""); (err != nil) != tt.wantErr {
				t.Errorf("GitRepository.Parse() error = %#v, wantErr %#v", err, tt.wantErr)
			}

			if !reflect.DeepEqual(r, tt.wantObj) {
				t.Errorf("DeepEqual r = %#v, wantObj %#v", r, tt.wantObj)
			}
		})
	}
}

func TestGitRepository_BitbucketParse(t *testing.T) {
	tests := []struct {
		name    string
		url     string
		branch  string
		sub     string
		wantObj *GitRepository
		wantErr bool
	}{
		{
			name:   "Parse Bitbucket Current Branch Repository",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2",
				DirPath:      "repository/atlassian/atlaskit-mk-2/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2",
				Path:         "",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Different Branch Repository",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/develop",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/src/develop",
				Path:         "",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "develop",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/develop.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/develop/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Repository Some Folder",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/develop",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/src/develop/services",
				Path:         "services",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "develop",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/develop.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/develop/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Repository Multiple Folders",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/website-constellation/",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/website-constellation",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/website-constellation/",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/website-constellation/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/develop",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/src/develop/services/website-constellation",
				Path:         "services/website-constellation",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "develop",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/develop.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/develop/[PATH]",
				DownloadType: DownloadPartialPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Repository Multiple Folders - 2",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/develop/services/website-constellation/gatsby-node.js",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/develop/services/website-constellation/gatsby-node.js",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/develop/services/website-constellation/gatsby-node.js",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/develop/services/website-constellation/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/develop",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/blob/develop/services/website-constellation/gatsby-node.js",
				Path:         "services/website-constellation/gatsby-node.js",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "develop",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/develop.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/develop/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Slashes Repository Name Before Define",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation/",
			branch: "ckharrl/CONCLOUD-68878-close-manager-propagation",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation/",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation",
				Path:         "",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
		{
			name:   "Parse Gitlab Root Directory Single File",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/README.md",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/README.md",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/README.md",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/master",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/src/master/README.md",
				Path:         "README.md",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "master",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/master.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/master/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		/*{
			name:   "Parse Bitbucket Slashes Repository Name",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
			branch: "",
			sub: "",
			wantObj: &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				RawUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				CloneUrl:    "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:   "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				DirPath:     "repository/atlassian/atlaskit-mk-2/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:      true,
				Protocol:    "https",
				Scheme:      "https",
				Hostname:    "bitbucket.org",
				RawPath:     "/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation",
				Path:        "",
				Owner:       "cli",
				Name:        "cli",
				DummyBranch: "gitd-branch",
				Branch:      "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:  "https://bitbucket.org/atlassian/atlaskit-mk-2/get/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
			},
			wantErr: false,
		},*/
		{
			name:   "Parse Bitbucket Slashes Repository Name File",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
			branch: "ckharrl/CONCLOUD-68878-close-manager-propagation",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2/src/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/",
				DirPath:      "repository/atlassian/atlaskit-mk-2/ckharrl/CONCLOUD-68878-close-manager-propagation",
				IsFile:       true,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2/blob/ckharrl/CONCLOUD-68878-close-manager-propagation/services/website-constellation/gatsby-node.js",
				Path:         "services/website-constellation/gatsby-node.js",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "ckharrl/CONCLOUD-68878-close-manager-propagation",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/ckharrl/CONCLOUD-68878-close-manager-propagation.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw/ckharrl/CONCLOUD-68878-close-manager-propagation/[PATH]",
				DownloadType: DownloadSingleFile,
			},
			wantErr: false,
		},
		{
			name:   "Parse Bitbucket Repository Fragment Url",
			url:    "https://bitbucket.org/atlassian/atlaskit-mk-2/#browser-support",
			branch: "",
			sub:    "",
			wantObj: &GitRepository{
				TempDir:      "",
				SSID:         "",
				Url:          "https://bitbucket.org/atlassian/atlaskit-mk-2",
				RawUrl:       "https://bitbucket.org/atlassian/atlaskit-mk-2/#browser-support",
				CloneUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2.git",
				RemoteUrl:    "git@bitbucket.org:atlassian/atlaskit-mk-2.git",
				QueryUrl:     "https://bitbucket.org/atlassian/atlaskit-mk-2",
				DirPath:      "repository/atlassian/atlaskit-mk-2/gitd-branch",
				IsFile:       false,
				Protocol:     "https",
				Scheme:       "https",
				Hostname:     "bitbucket.org",
				RawPath:      "/atlassian/atlaskit-mk-2",
				Path:         "",
				Owner:        "atlassian",
				Name:         "atlaskit-mk-2",
				DummyBranch:  "gitd-branch",
				Branch:       "",
				ArchiveUrl:   "https://bitbucket.org/atlassian/atlaskit-mk-2/get/.zip",
				FileUrl:      "https://bitbucket.org/atlassian/atlaskit-mk-2/raw//[PATH]",
				DownloadType: DownloadFullPackage,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			r := &GitRepository{
				TempDir:     "",
				SSID:        "",
				Url:         "",
				RawUrl:      tt.url,
				CloneUrl:    "",
				RemoteUrl:   "",
				DirPath:     "",
				IsFile:      false,
				Protocol:    "",
				Scheme:      "",
				Hostname:    "",
				RawPath:     "",
				Path:        "",
				Owner:       "",
				Name:        "",
				DummyBranch: "gitd-branch",
				Branch:      tt.branch,
				ArchiveUrl:  "",
				FileUrl:     "",
			}
			if err := r.Parse(tt.sub, DirectionNone, ""); (err != nil) != tt.wantErr {
				t.Errorf("GitRepository.Parse() error = %#v, wantErr %#v", err, tt.wantErr)
			}

			if !reflect.DeepEqual(r, tt.wantObj) {
				t.Errorf("DeepEqual r = %#v, wantObj %#v", r, tt.wantObj)
			}
		})
	}
}
